source 'https://rubygems.org'

Encoding.default_external = Encoding::UTF_8

gem 'chronic'
gem 'logging'

group :test do
  gem 'rspec'
  gem 'spork'
  gem 'simplecov'
end

group :development do
  gem 'bundler'
  gem 'jeweler'
  gem 'redcarpet'
  gem 'yard'
end
